Algoritmo "lojavendeseusprodutos"
// 
//  
// Descrição   :
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/11/2022
var
valor,entrada,prestacoes:real
inicio
// Seção de Comandos
escreval("Escreva valor da compra!:")
leia (valor)
entrada<-(valor*0.4)
prestacoes<-(valor-entrada)/2
escreval("")
escreval("")
escreval ("Entrada igual=",entrada)
escreval("")
escreval ("Prestações igual=",prestacoes)
fimalgoritmo