Algoritmo "volumedeumalatadeóleo"
// 
//  
// Descrição   :
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/11/2022
var
altura,raio,volume :real
inicio
// Seção de Comandos
escreva("Qual e a altura do recipiente?:")
leia(altura)
escreval("")
escreva("Qual o raio do recipiente?:")
leia(raio)
escreval("")
volume <-(raio*raio*pi)*altura
escreval("O volume do recipiente é:",volume)
fimalgoritmo