algoritmo "hipotenusaT"
//Faça um programa que receba o valor dos catetos de um triângulo, calcule e mostre o valor da hipotenusa.
//Nome: Alexandre Donisete velho
//Professor: Coradine
//Discipina: Algoritmo
//Declaração de variaveis
var
lado1,lado2,hipotenuza:real
inicio
escreva("-digite o lado A-")
  leia(lado1)
  escreva("digite o lado B-")
  leia(lado2)
  hipotenuza<-(lado1*2)+(lado2*2)
  escreval("hipotenuza=",hipotenuza)



fimalgoritmo
