Algoritmo "QuadradodeumNumero"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/11/2022
Var
// Seção de Declarações das variáveis 
I: inteiro
IaoQ: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("")
escreva("Digite um numero inteiro:")
leia(I)
escreval("")
IaoQ <- I^2
Escreva("Valor inteiro ao quadrado:", IaoQ)
escreval("")

Fimalgoritmo